INSERT INTO role (id,name) SELECT 1,"ROLE_USER"
 WHERE NOT EXISTS (SELECT id FROM role WHERE id = 1);

 INSERT INTO role (id,name) SELECT 2,"ROLE_ADMIN"
  WHERE NOT EXISTS (SELECT id FROM role WHERE id = 2);